# Alertmanager Config for Slack Alerts
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yaml: |
    route:
      receiver: "slack-notifications"
    receivers:
      - name: "slack-notifications"
        slack_configs:
          - channel: "#alerts"
            api_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
            text: "{{ .CommonAnnotations.summary }}"
